### ISSUE TITLE
routines aren't working

### ISSUE THREAD

**Issue by niddelicious** [niddelicious/ailicious#1]
The automatic routines for fetching a new access_token are not run, because the bot is started incorrectly

Restructuring may be required to make sure that a non-blocking instance of the twitchio bot is ran with the bot.run() command, because otherwise the routines are not working as expected

Might actually be simpler to implement a different system altogether for timed events.

**Comment by gnomefire** [comment]
This is a pretty simple fix - on line 47  of `TwitchChat.py`  
change 
`await self.bot.start()`
to
`await self.bot.run()`

`.start()` is a coroutine of `.run()` , so it's not needed

**Comment by niddelicious** [comment]
> This is a pretty simple fix - on line 47 of `TwitchChat.py` change `await self.bot.start()` to `await self.bot.run()`
> 
> `.start()` is a coroutine of `.run()` , so it's not needed

I've noticed that run() is required for the routines to work, yes. But from my testing it's not as simple as replacing start() with run(), because that is blocking and will hinder the command line.
I've been experimenting with calling run() in a different thread, but that still doesn't seem to solve the problem.

**Comment by gnomefire** [comment]
Bummer, well, when I get a chance I will dig into it.  I've already added a weather command and I am working on implementing a universal command interpreter

**Comment by niddelicious** [comment]
.run() needs to be called in its own thread to not be blocking.
init() also needs to be called in its own thread, otherwise .run() will complain that the event loop is already running.

I'm working on a good way to fix it, while still having access to the status of the module, somehow.

**Comment by niddelicious** [comment]
https://github.com/niddelicious/ailicious/tree/twitch_token_expiring_bug gets routines working, but breaks a clean exit 🤔

**Comment by niddelicious** [comment]
Resolved with https://github.com/niddelicious/ailicious/commit/ffce3db63e8ce706ac3540757f11e17e898655fc
